### ISSUE TITLE
Empty labels

### ISSUE THREAD

**Issue by dd1982** [labelle-org/labelle#62]
Just installed labelle and trying to use it with my LabelManager 420P with 6mm tape.

Running the following renders a label where I can see only the upper parts of the characters;
labelle "Hello world"

Running the following renders empty labels;
labelle --tape-size-mm 6 "Hello world"
labelle --test-pattern 1

What am I missing?

**Comment by maresb** [comment]
Hey @dd1982! We have been trying to add support for smaller tapes, see #54 for discussion of some of the complications.

I just created a new Labelle release (v1.2.3) that includes our new [calibration procedure](https://github.com/labelle-org/labelle/blob/main/doc/margin-calibration-howto.md). In short all you need to do is upgrade to that and run

```bash
labelle --sample-pattern 64
```

then take a photo and paste the photo into this issue. That will allow us to determine the offsets for your particular printer. Then if we switch you to the experimental branch from #54 you will hopefully be able to print.

**Comment by dd1982** [comment]
Ah, does it matter which size of tape I have? Could do the same for other tape sizes if it helps - besides the 6mm pictured below I also have 9mm, 12mm and 19mm tapes.

![image](https://github.com/user-attachments/assets/a1824390-58ca-4e42-89de-45e48ea2d171)

**Comment by maresb** [comment]
Ah, the print head is larger than I was expecting. Looks like 128 px.

Could you please repeat with

```
labelle --sample-pattern 130
```

And if you could do it for all tape sizes that would be super amazing!!! Thanks a lot!

**Comment by dd1982** [comment]
No, problem, 

![image](https://github.com/user-attachments/assets/91a62a5d-94a8-45b8-8b50-7065d7052742)

**Comment by maresb** [comment]
This is very helpful, thanks @dd1982!!

Here is my interpretation of the results:

The print head size is indeed 128.
6mm: 44-86
9mm: 35-98
12mm: 28-105
19mm: full range

It would be great if another maintainer could verify my counting.

**Comment by maresb** [comment]
@dd1982, could you please try changing to our development branch via

```python
pipx install --force git+https://github.com/labelle-org/labelle@develop
```

I made some adjustments to the config in #63 that will hopefully resolve the issues. Please let us know how it works. Thanks!!

**Comment by dd1982** [comment]
Just back after the weekend. Changed to development branch and tested the following quickly;

labelle "Hello world"
labelle --tape-size-mm 6 "Hello world"

Results;
![image](https://github.com/user-attachments/assets/b7d68b42-cd47-4e41-973f-f869c1a983cb)

Running labelle-gui produces the following error message;

`Traceback (most recent call last):
  File "/home/petter/.local/pipx/venvs/labelle/lib/python3.10/site-packages/labelle/gui/gui.py", line 108, in _on_settings_changed
    height_px=self._dymo_labeler.label_height_px,
  File "/home/petter/.local/pipx/venvs/labelle/lib/python3.10/site-packages/labelle/lib/devices/dymo_labeler.py", line 277, in label_height_px
    return self.tape_print_properties.usable_tape_height_px
  File "/home/petter/.local/pipx/venvs/labelle/lib/python3.10/site-packages/labelle/lib/devices/dymo_labeler.py", line 305, in tape_print_properties
    raise ValueError(
ValueError: Unsupported tape size 24mm. Supported sizes: [6, 9, 12, 19]mm
Aborted (core dumped)
`

**Comment by maresb** [comment]
Ah, very nice results with the `--tape-size-mm 6` command! I'm glad we got it working.

And yes, there are some pretty major problems with the `develop` branch which is why it isn't yet merged to 'main'.

**Comment by tomers** [comment]
I got this error too, when working on a new labeler (Dymo LabelWriter 550).
This is my current understanding of the issue (I am just learning it, so I might be wrong):
The thing is that during initialization, the simulator configuration is momentarily selected, until the real configuration is detected. In that time, the tape size from the labeler is used, but it must match the supported tape sizes of the simulator configuration. In case it isn't, an exception is thrown.
A workaround would be to add the union of all supported label sizes to the simulator configuration. However, I don't think this is the way to go. I am not sure yet what is the purpose of the simulator configuration, but I think it stands in the way on regular flow in which a labeler device is connected.
I think that no configuration state should be supported. In that state the UI should not crash. Preferrably it should hide all non-relevant widgets, until a real configuration is set.

**Comment by dd1982** [comment]
> Ah, very nice results with the `--tape-size-mm 6` command! I'm glad we got it working.

Yes, though it seems it's not perfectly aligned vertically with more white space above the text than below. Here's a label from the labeller on top and two from labelle on the bottom.

![image](https://github.com/user-attachments/assets/bebe8079-5717-47b3-9a51-eadaba79f766)

**Comment by maresb** [comment]
> I think that no configuration state should be supported. In that state the UI should not crash. Preferrably it should hide all non-relevant widgets, until a real configuration is set.

The simulator configuration is super weird. (Maybe it would make more sense if it were renamed the "fallback configuration"?) On the other hand for the GUI I don't understand why you would want to hide anything except for the print button when a printer isn't connected. As far as I can tell our abstract label specification doesn't depend on label width, so it seems reasonable to me to allow the user to specify the label before choosing a print config, and also to be able to preview how that specification would render on various widths.

> Yes, though it seems it's not perfectly aligned vertically with significantly more white space above the text than below it. Here's a label from the labeller on top which is more centered and two from the following labelle commands on the bottom;

Yes, thank you for pointing this out. We should indeed support custom offsets rather than assuming the label is centered on the print head.

There is an open question of: for different instances of the same combination of "printer model" and "label width", how much variation is there in the offset? In other words, if someone else has a 420P with a 6mm tape, how close would I come to reproducing the same offsets we computed above? My feeling is +/- 1 px, but I don't have much data to back that up.

**Comment by FaBjE** [comment]
> The simulator configuration is super weird.

For the GUI it is, it was a "solution" for the CLI test functions where you render to CLI output or an image.
That rendering needs margins info as well. Goal was to keep those test functions working without a printer connected. Fallback config might be a better name indeed.

> We should indeed support custom offsets rather than assuming the label is centered on the print head.

I'm just wondering, as I see two labels (one good, one offset) if there were made on the same printer/tape.
If so, it is more a problem of variation in the label/printhead alignment than a "fixed offset"

**Comment by tswelectronics** [comment]
I have an issue with my 420P where it is seems to have a large margin at the top and it pushes the text off the bottom so I only see the top half of the text on the tape. This is for 12mm tape. When I changed the tape size to 19mm whilst having a 12nmm tape in it got better but it isn't right. Maybe it's a scaling issue? 

![IMG_3667](https://github.com/user-attachments/assets/4afe5691-4794-4cf9-82b8-563858cf5bed)

**Comment by TechZ-S** [comment]
Same here.
I have attached two prints which has created with the following commands:

```
labelle --sample-pattern 130
labelle --tape-size-mm 12 "Hello World"

```


![dymo_420_12mm](https://github.com/user-attachments/assets/06d6c2dc-31ad-4281-8082-11698396829e)

**Comment by hernot** [comment]
By now it is 2026 so a long time since last tests. I just have bought my 420 P which is 4th Generation (see attchaded output of lsusb). 


[device-info-420p.log](https://github.com/user-attachments/files/26660271/device-info-420p.log)

@maresb i can confirm your countings at least for the 19mm and 12mm tape my 9mm did not yet arrive
Looking at the cartridges it seems that the black color tape is smaller than the label. 

On my 19mm it is about 18mm mounted centric to the label. And explains the perfectly the margins on the image. On the test print of the 12mm label on top there is no margin and on the bottom it has 1.5mm. Checking again the color tape than this margin is quite well confined with the location of the color tape it seems as if this tape would be just 10.5mm wide and perfectly aligned with the top edge of the label. (sorry for the bit blurry image of the back side was not better possible).

Therefore

Tape    | counts | margin bottom | margin top | color tape width | DPI | mm / pix 
--- | --- | --- | ---  | --- | --- | --- 
19mm | 2(3) - 128 | 0.5mm  | 0.5mm | 18mm | ~180 | ~0.14  
12mm | 32 - 106 | 1.5mm  | 0 mm | 10.5mm | ~180 | ~0.14
9mm |  |  |  |  | |

Therefore it could also be that the print head has actually 130 pixels or even /132 pixels. But that does not really matter as the the color tapes are seemingly smaller and are the more likely cause for bottom and top cuts. Especially as it is not even guaranteed that they are mounted centered with respect to the cartridge and/or the label strip. In case of my 19mm tape that would mean that about 4 pixels ( 1mm ) at top and bottom should be avoided as they may be not covered by the transfer tape. Under the assumption that print head resolution per mm does not change just cause the 420P is told to print now on a 12mm tape. On my 12 mm tape it would be even 6 to 8 pixel (1.5mm) which have to be spared to avoid the cropped text and images cause of width and miss alignment of the 10.5mm color tape.

Images

Printhead Test
<img width="1512" height="3432" alt="Image" src="https://github.com/user-attachments/assets/9a9a1a10-c7d8-40ba-aa9f-f00ec0a0a9ce" />

19mm label calibration (after removing and reinserting cartridge)
<img width="1281" height="561" alt="Image" src="https://github.com/user-attachments/assets/7da91dd9-4dce-460c-9b0e-5cf10ad1db5b" />

12mm label calibration 
<img width="1628" height="512" alt="Image" src="https://github.com/user-attachments/assets/d12ca6ac-55d7-45e1-a2b3-4f9c7cfa58ef" />

12mm cartridge back view - Transfer tape alignment
<img width="3135" height="1326" alt="Image" src="https://github.com/user-attachments/assets/3cb4af6d-b0f9-47bc-a677-7f216be4bf24" />

 
All the tests were done using the main branch which seems to be the latest and most up to date as of today. Running here 64bit Ubuntu 22.04 based system here. With python 3.10 as default python.  

By the way is there a file where the calibration is stored per device or is this still work in progress (*). If there is anything i can help including python implementation just let me know. I guess i find some time to spare for better and nicer labels prepared on computer.
 
(*) on develop branch this infromation seems to be stored in constants.py. but that branch is behind main and has not received any commits and merges since 2 years.
